version: '3.5'
services:
    php:
        build:
            context: ./docker/php
        working_dir: /var/www
        networks: &networks
            - "wonde_network"
        volumes: &volumes
            - shared:/shared:cached
            - ./:/var/www
        environment: &php-env
            - "COMPOSER_ALLOW_XDEBUG=1"
            - "PHP_IDE_CONFIG=serverName=wonde.test"

    php-xdebug:
        build:
            context: ./docker/php-xdebug
        working_dir: /var/www
        networks: *networks
        volumes: *volumes
        environment: *php-env

    mysql:
        image: mysql:8-oracle
        networks: *networks
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            - "MYSQL_DATABASE=wonde_test"
            - "MYSQL_ROOT_PASSWORD=secret"
        ports:
            - '${MYSQL_PORT:-3306}:3306'

    node:
        image: node:alpine3.18
        working_dir: /var/www
        tty: true
        networks: *networks
        expose:
            - '5173:5173'
        volumes: *volumes

    web:
        build:
            context: ./docker/nginx
        depends_on:
            - php
        working_dir: /var/www
        networks: *networks
        ports:
            - '${APP_PORT:-80}:80'
        volumes: *volumes

volumes:
    dbdata:
    shared:

networks:
    wonde_network:
